const menu=document.getElementById("menu");
const game=document.getElementById("qc");
const caps=document.getElementById("caps");
const sts=document.getElementById("sts");

//El diccionario ☺
const  dcc=[
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"colima",
        cap:"colima"
    },
    {
        st:"michoacan",
        cap:"morelia"
    },
    {
        st:"sinaloa",
        cap:"culiacan"
    },
    {
        st:"chihuahua",
        cap:"chihuahua"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    {
        st:"jalisco",
        cap:"guadalajara"
    },
    ]